
var appname = '',
	appVersionStr = '',
	appIconStr = '',
	appInstallURL = '',
	appdescriptionStr = '',
	appdeveloperStr = '',
	appcategoryStr = '',
	screenshots1Str = '',
	screenshots2Str = '',
	screenshots3Str = '',
	screenshots4Str = '',
	screenshots5Str = '';




function setAppInfo(appnum){
	appname = window['app'+appnum][0];
	appVersionStr = window['app'+appnum][1];
	appIconStr = window['app'+appnum][2];
	appInstallURL = window['app'+appnum][3];
	appdescriptionStr = window['app'+appnum][4];
	appdeveloperStr = window['app'+appnum][5];
	appcategoryStr = window['app'+appnum][6];
	screenshots1Str = window['app'+appnum][7];
	screenshots2Str = window['app'+appnum][8];
	screenshots3Str = window['app'+appnum][9];
	screenshots4Str = window['app'+appnum][10];
	screenshots5Str = window['app'+appnum][11];
	
	
}

//Array structure
//var appverialble = ["AppName", "AppVersion", "AppIconAddress", "AppConfigURL", "AppDescription", "AppDeveloper", "AppCategory", "AppScreeshot1", "AppScreenshot2", "AppScreenshot3", "AppScreenshot4", "AppScreenshot5"];
//var app001 = ["","","","","","","","","","","",""];


// --- iNuclearApp ---
var app001 = ["Android Theme","Version 1.0","../../settings/android/iPhone.png"," https://inuclearapp.org/beta/themes/androidtheme.mobileconfig ","iNuclearApp comes with a variety of themes and UI changes. This page downloads an android theme. Enjoy!","iNuclearApp","Themes","","","","",""];
var app002 = ["iTweakOS","Version 1.0","http://onuniverse-assets.imgix.net/3CC8C49B-91C7-40A8-A283-D754037C3DEB.jpg"," https://itweakos.store/install.mobileconfig ","iTweakOS is a cydia alternative which can let you download 3rd Party Apps such as Hacked Games, Paid Apps/Games and/or Cydia Tweaks without a Jailbreak or a PC.","CaspXD","Cydia Alternative","../../settings/screenshots/itweakos1.png","../../settings/screenshots/itweakos2.png","","","",""];
var app003 = ["BetaStore","Version 1.0","http://raw.githubusercontent.com/APPLEH4CKZ/AppleBetas/master/Logos/CA8D1AD8-3B15-4245-8939-168F8F7673D9.jpeg"," http://x-applebetas.weebly.com/uploads/1/2/1/9/121961376/betastoresigned.mobileconfig ","Download Apple Betas, Apple Wallpapers, Cool Shortcuts and more!","APPLEH4CKZ","Cydia Alternative","../../settings/screenshots/betastore1.png","../../settings/screenshots/betastore2.png","","","",""];
var app004 = ["Respring+","Version 1.0","../../settings/icons/respring.jpg"," appleprintcenter:// ","Quick way to respring your device. One button away! Go ahead, try.","iNuclearApp","Other","../../settings/screenshots/respring1.jpg","../../settings/screenshots/respring2.jpg","","","",""];
var app005 = ["iNoLabels","Version 1.0","../../settings/icons/jailbreak.png"," https://inuclearapp.org/beta/themes/nolabels.mobileconfig ","iNuclearApp comes with a variety of themes and UI changes. This page downloads iNoLabels which hides all the labels. Enjoy!","iNuclearApp","Themes","../../settings/screenshots/inolabels1.png","../../settings/screenshots/inolabels2.png","","","",""];
var app006 = ["NoDockBG","Version 1.0","../../settings/icons/jailbreak.png"," https://inuclearapp.org/beta/themes/nodockbg.mobileconfig ","iNuclearApp comes with a variety of themes and UI changes. This page downloads NoDockBG which hides the dock's background for a cleaner look. Enjoy!","iNuclearApp","Themes","../../settings/screenshots/nodockbg1.png","../../settings/screenshots/nodockbg2.png","","","",""];
var app007 = ["CleanHouse","Version 1.0","../../settings/icons/cleanhouse.png"," https://inuclearapp.org/beta/themes/nolabelsnodockbg.mobileconfig ","iNuclearApp comes with a variety of themes and UI changes. This page downloads iNoLabels and NoDockBG which is a combination of both tweaks. There will be no dock background and no labels. Enjoy!","iNuclearApp","Themes","../../settings/screenshots/cleanhouse1.png","../../settings/screenshots/cleanhouse2.png","","","",""];
var app008 = ["Facetune","Version 2.6.6","../../settings/icons/facetune.jpg","http://185.246.209.74/ipa/912163516.ipa","Facetune is a fun and powerful portrait & selfie photo editor! #1 Photo and Video App in 127 countries!","Lightricks Ltd.","Photo & Video","../../settings/screenshots/facetune1.jpg","../../settings/screenshots/facetune2.jpg","","",""];
var app009 = ["DownCloud","Version 2.0","","","","","","","","","",""];




var app031 = ["Lite Express","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/lite_express.png","http://iextras.org/themes/config/let.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/lite_express.png","","","",""];
var app032 = ["Stock Qetto","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/stock_qetto.png","http://iextras.org/themes/config/stock-qetto-hd.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/stock_qetto.png","","","",""];
var app033 = ["Gold BlackBerry","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/gold_blackberry.png","http://iextras.org/themes/config/gold-blackberry-hd.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/gold_blackberry.png","","","",""];
var app034 = ["Blue Water Theme","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/blue_water.png","http://iextras.org/themes/config/bwt.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/blue_water.png","","","",""];
var app035 = ["Blue Metal Theme","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/blue_metal.png","http://iextras.org/themes/config/bmt.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/blue_metal.png","","","",""];
var app036 = ["Anroid Blawb","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/anroid_blawd.png","http://iextras.org/themes/config/anroid-blawb-hd.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/anroid_blawd.png","","","",""];
var app037 = ["Metalic Supernova","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/behind_the_snow.png","http://iextras.org/themes/config/ms.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/metalic_supernova.png","","","",""];
var app038 = ["Yellow Honey","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/yellow_honey_theme.png","http://iextras.org/themes/config/yh.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/yellow_honey_theme.png","","","",""];
var app039 = ["Wood Combination","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/wood_combination_theme.png","http://iextras.org/themes/config/wc.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/wood_combination_theme.png","","","",""];
var app040 = ["Sharp Eye Theme","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/sharp_eye_theme.png","http://iextras.org/themes/config/se.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/sharp_eye_theme.png","","","",""];
var app041 = ["Sea Waves Theme","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/sea_waves_theme.png","http://iextras.org/themes/config/sw.mobilechttp://iextras.org/themes/apps/Red_Glossy_Theme.htmlonfig","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/sea_waves_theme.png","","","",""];
var app042 = ["Red Glossy Theme","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/red_glossy_theme.png","http://iextras.org/themes/config/rg.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/red_glossy_theme.png","","","",""];
var app043 = ["Red Awesome","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/red_awesome_Theme.png","http://iextras.org/themes/config/ra.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/red_awesome_theme.png","","","",""];
var app044 = ["Orkut Pore Theme","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/orkut_pore_theme.png","http://iextras.org/themes/config/op.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/orkut_pore_theme.png","","","",""];
var app045 = ["Mummy Theme","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/mummy_theme.png","http://iextras.org/themes/config/mu.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/mummy_theme.png","","","",""];
var app046 = ["Blue Ash","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/blue_ash.png","http://iextras.org/themes/config/ba.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/blue_ash.png","","","",""];
var app047 = ["Blue Print","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/blue_print.png","http://iextras.org/themes/config/blue-print.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/blue_print.png","","","",""];
var app048 = ["Green Lantern","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/green_lantern.png","http://iextras.org/themes/config/glt.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/green_lantern.png","","","",""];
var app049 = ["Galaxy X Theme","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/galaxy_x_theme.png","http://iextras.org/themes/config/gxt.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/galaxy_x.png","","","",""];
var app050 = ["Metro Silver HD","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/metro_silver_hd.png","http://iextras.org/themes/config/metro-silver-hd.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/metro_silver_hd.png","","","",""];
var app051 = ["Metro Blue","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/metro_blue.png","http://iextras.org/themes/config/metro-blue-hd.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/metro_blue.png","","","",""];
var app052 = ["iLight HD","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/ilight_hd.png","http://iextras.org/themes/config/ilight-hd-themes.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/ilight.png","","","",""];
var app053 = ["Green Android","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/green_an.png","http://iextras.org/themes/config/green-android-hd.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/green_android.png","","","",""];
var app054 = ["Wood Fusion","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/wood_fu.png","http://iextras.org/themes/config/wood-fusion-hd.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/wood_fu.png","","","",""];
var app055 = ["Black Gcons","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/black_gcons.png","http://iextras.org/themes/config/black-gcons-hd.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/black_gcons.png","","","",""];
var app056 = ["Yellow Honeycomb","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/yellow_honeycomb.png","http://iextras.org/themes/config/yellow-honeycomb-hd.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/yellow_honey_theme.png","","","",""];
var app057 = ["Windows 8","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/windows_8.png","http://iextras.org/themes/config/windows-8.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/windows_8.png","","","",""];
var app058 = ["Blue Velvet","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/blue_velvet.png","http://iextras.org/themes/config/blue-belvet.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/Blue_Velvet.png","","","",""];
var app059 = ["Dreams","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/dreams.png","http://iextras.org/themes/config/dr.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/dream.png","","","",""];
var app060 = ["Hello Kitty","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/hello_kitty.png","http://iextras.org/themes/config/hk.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/hello_kitty.png","","","",""];
var app061 = ["Crack Mud","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/crack_mud.png","http://iextras.org/themes/config/cm.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/crack_mud.png","","","",""];
var app062 = ["Ancient Gate","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/ancient_gate.png","http://iextras.org/themes/config/ag.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/ancient_gate.png","","","",""];
var app063 = ["Mirror Theme","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/mirror_theme.png","http://iextras.org/themes/config/me.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/mirror_theme.png","","","",""];
var app064 = ["Magic Wood Man","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/magic_wood_man.png","http://iextras.org/themes/config/mwm.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/magic_wood_man.png","","","",""];
var app065 = ["Magic Cold Man","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/magic_cold_man.png","http://iextras.org/themes/config/mcm.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/magic_cold_man.png","","","",""];
var app066 = ["Love Angel Theme","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/love_angel_theme.png","http://iextras.org/themes/config/la.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/love_angel_theme.png","","","",""];
var app067 = ["Funny Devil","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/funny_devil.png","http://iextras.org/themes/config/d.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/funny_devil.png","","","",""];
var app068 = ["Floting grass","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/floting_grass.png","http://iextras.org/themes/config/fg.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/floting_grass.png","","","",""];
var app069 = ["Behind the Snow","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/behind_the_snow.png","http://iextras.org/themes/config/bts.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/behind_the_snow.png","","","",""];
var app070 = ["Blossom Circle","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/blossom_circle.png","http://iextras.org/themes/config/bc.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/blossom_circle.png","","","",""];
var app071 = ["Thug Pets Theme","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/thug_pets_theme.png","http://iextras.org/themes/config/tp.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/thug_pets_theme.png","","","",""];
var app072 = ["Red Bubble Theme","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/red_bubble_theme.png","http://iextras.org/themes/config/rb.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/red_awesome_theme.png","","","",""];
var app073 = ["Purple Art Theme","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/purple_art_theme.png","http://iextras.org/themes/config/pa.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/purple_art_theme.png","","","",""];
var app074 = ["Metro Theme","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/metro_theme.png","http://iextras.org/themes/config/mpat.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/metro_theme.png","","","",""];
var app075 = ["Hex star","","http://taig9.com/12/cydia/images/app_install_page/idiy/icon/hex_star.png","http://iextras.org/themes/config/h.mobileconfig", "iNuclearApp comes with a variety of themes and UI changes. This page downloads a theme. Enjoy!", "iNuclearApp", "Themes","http://taig9.com/12/cydia/images/app_install_page/idiy/screenshot/hex_star.png","","","",""];